AUTHOR_NAME="Jérémie DECOCK"
AUTHOR_EMAIL="jd.jdhp@gmail.com"
AUTHOR_WEB_SITE="www.jdhp.org"

COPYRIGHT_NOTICE="Copyright (c) 2016 ${AUTHOR_NAME} (${AUTHOR_WEB_SITE})"

PROJECT_INITIAL_DATE="2016-12-24"
PROJECT_SHORT_DESC="Play the classic Tic-Tac-Toe game."

PROJECT_NAME="TicTacToe"
PYTHON_PACKAGE_NAME="tictactoe"
PYTHON_PACKAGE_NAME_SPACE="jdhp"
# if PYTHON_PACKAGE_NAME_SPACE != ""
PYTHON_PACKAGE_FULL_NAME="${PYTHON_PACKAGE_NAME_SPACE}.${PYTHON_PACKAGE_NAME}"
PYTHON_PACKAGE_FULL_PATH="${PYTHON_PACKAGE_NAME_SPACE}/${PYTHON_PACKAGE_NAME}"
# else
#PYTHON_PACKAGE_FULL_NAME="${PYTHON_PACKAGE_NAME}"
#PYTHON_PACKAGE_FULL_PATH="${PYTHON_PACKAGE_NAME}"

PROJECT_GITHUB_ACCOUNT="jeremiedecock"
PROJECT_GITHUB_REPOSITORY_NAME="tictactoe-py"

PROJECT_GITHUB_URL="https://github.com/${PROJECT_GITHUB_ACCOUNT}/${PROJECT_GITHUB_REPOSITORY_NAME}"
PROJECT_ISSUE_TRACKER_URL="https://github.com/${PROJECT_GITHUB_ACCOUNT}/${PROJECT_GITHUB_REPOSITORY_NAME}/issues"

PROJECT_PYPI_NAME="jdhp-${PYTHON_PACKAGE_NAME}"
PROJECT_PYPI_URL="https://pypi.python.org/pypi/${PROJECT_PYPI_NAME}"

PROJECT_WEB_SITE_URL="http://www.jdhp.org/software_en.html#${PYTHON_PACKAGE_NAME}-py"

PROJECT_ONLINE_DOCUMENTATION_URL="http://${PYTHON_PACKAGE_NAME}.readthedocs.org"
PROJECT_ONLINE_API_DOCUMENTATION_URL="http://${PYTHON_PACKAGE_NAME}.readthedocs.org/en/latest/api.html"
